export const ERROR_CODES = {
  GENERIC: 0,
  INVALID_EMAIL: 1,
  INVALID_EMAIL_DOMAIN: 2,
  INVALID_EMAIL_USERNAME: 3,
  EMAIL_ALREADY_SUBSCRIBED: 4,
  TIMEOUT: 5
}

export const SUCCESS_CODES = {
  GENERIC: 0,
  CONFIRM_EMAIL_ADDRESS: 1
}
